name: GitHub Pages

# 手動トリガー
on:
  workflow_dispatch:

jobs:
  build:
    # Webブラウザー向けに静的コンテンツのビルドを行う
    name: Build static contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.repository }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys:
            ${{ runner.os }}-${{ github.repository }}-

      - name: Install dependencies
        run: yarn
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build for production
        run: yarn run build

      - name: Upload result for next job
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  deploy:
    # ビルドした静的コンテンツを GitHub Pages にデプロイする
    name: Push to gh-pages branch and Deploy for GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download result from previous job
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Push to gh-pages branch and Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
