name: GitHub Packages

# 手動トリガー
on:
  workflow_dispatch:

# 環境変数
env:
  # Dockerイメージ名
  IMAGE_NAME: site
  # Dockerレジストリ名
  IMAGE_REGISTRY: docker.pkg.github.com

jobs:
  build_and_push:
    # DockerイメージをビルドしてPackagesにプッシュ
    name: Build static contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          IMAGE_ID=${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=${IMAGE_ID,,}
          echo "::set-env name=IMAGE_ID::$IMAGE_ID"
          echo "::set-env name=IMAGE_VERSION::latest"

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $IMAGE_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker pull $IMAGE_ID:$IMAGE_VERSION || true
          docker build \
            --cache-from $IMAGE_ID:$IMAGE_VERSION \
            --target prod \
            -t $IMAGE_NAME \
            .

      - name: Push image
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
